### ISSUE TITLE
What is "sni-proxy" for? 

### ISSUE THREAD

**Issue by luzbel** [strongloop/apiconnect-docker#11]
What is "sni-proxy" for? Is something related to https://www.ibm.com/developerworks/rfe/execute?use_case=viewRfe&CR_ID=92900  ? 
 can you link manager and datapower without sni-proxy?

**Comment by kraman** [comment]
@luzbel The docker containers all require https over port 443. Since this is running with docker-compose its not really possible for all the containers to be exposed on port 443 on the host machine. 

The SNI proxy basically uses nginx to demux the requests to the appropriate containers.

**Comment by luzbel** [comment]
ok, clear. Thanks!!!
