### ISSUE TITLE
Running on Docker for Windows?

### ISSUE THREAD

**Issue by QAnders** [strongloop/apiconnect-docker#28]
Is there any container created that is running on Docker for Windows (not Toolbox/Oracle VirtualBox)?

Both DataPower and IBM MQ runs fine in Docker for Windows (Linux container) but for this container all startup scripts are created for Linux it seems...

**Comment by aldenchan** [comment]
-- no, but one of the closed issue indicate how to resolve this:

>  given I am running docker-tool box on windows with VM - by taking following measures able to start containers without any problem
>  dos2unix on script file to remove any doc linefeeds
> 
> from dir "apiconnect-docker"
>  find /path -type f -print0 | xargs -0 dos2unix --

**Comment by QAnders** [comment]
Runs fine on Windows 10 Docker4Win!

Requires 9 GB memeory in Docker though! Won't start with 8 GB only!
