### ISSUE TITLE
Ability to update APIC network settings (DNS and static hosts)

### ISSUE THREAD

**Issue by geekosphere-net** [strongloop/apiconnect-docker#33]
I am not able to access the APIC Management console as I am running this container behind a reverse proxy (https://traefik.io/) and need to be able to update the Gateway endpoint as a static address.

In the on-prem I just ssh and then
`net add etchost address a.b.c.d hostname api.myco.com
`
but I don't see how to do that with the Docker image.

**Comment by QAnders** [comment]
Have a look at this: https://github.com/ibm-apiconnect/pot-onprem-core/blob/5060/docker/docker-compose.yaml

See all those ".think.ibm"?
Replace them with your domain, e.g. ".traefik.io" and you'll find the API Manager at https://mgr.traefik.io/apim/ and Cloud Manger at https://mgr.traefik.io/cmc/
NB! Closing front-slash is a must!

If you need localhost access add "127.0.0.1 mgr.traefik.io" to your hosts file.

**Comment by geekosphere-net** [comment]
Thanks, that works (I had a misunderstanding of how the private ibmnet network was working.
